version: "3.9"

services:
  docker_db:
    image: postgres:9.6.21-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgresql_data:/var/lib/postgresql
  daemon:
    build: .
    entrypoint: ['python', 'run.py']
    command: -c config/schema.yaml -s stdout postgres -i 30
    environment:
      - DB_ADDR=docker_db
    volumes:
      - .:/code
    depends_on:
      - docker_db
